name: mata_uang
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  edge_detection: ^1.1.2
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  path: ^1.8.0
  tflite_flutter: ^0.9.1
  tflite_flutter_helper:
    git:
      url: https://github.com/filofan1/tflite_flutter_helper.git
      ref: 783f15e5a87126159147d8ea30b98eea9207ac70
  flutter_tts: ^3.7.0
  intl: ^0.18.1
  tutorial_coach_mark: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
